COUNTRY_ZOOM = {
    "Austria": 5.6,
    "Canada": 3.7,
    "Chile": 3.5,
    "Czechia": 5.2,
    "Finland": 4.2,
    "Italy": 5.0,
    "Japan": 4.6,
    "Norway": 4.2,
    "Slovenia": 5.6,
    "Spain": 4.8,
    "Sweden": 4.2,
    "Switzerland": 5.3,
    "Türkiye": 4.2,
    "United Kingdom": 4.0,
    "United States": 3.3,
}

US_STATES = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]

CANADA_PROVINCES = [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon",
]

JAPAN_PREFECTURES = [
    "Aichi",
    "Akita",
    "Aomori",
    "Chiba",
    "Ehime",
    "Fukui",
    "Fukuoka",
    "Fukushima",
    "Gifu",
    "Gunma",
    "Hiroshima",
    "Hokkaido",
    "Hyogo",
    "Ibaraki",
    "Ishikawa",
    "Iwate",
    "Kagawa",
    "Kagoshima",
    "Kanagawa",
    "Kochi",
    "Kumamoto",
    "Kyoto",
    "Mie",
    "Miyagi",
    "Miyazaki",
    "Nagano",
    "Nagasaki",
    "Nara",
    "Niigata",
    "Oita",
    "Okayama",
    "Okinawa",
    "Osaka",
    "Saga",
    "Saitama",
    "Shiga",
    "Shimane",
    "Shizuoka",
    "Tochigi",
    "Tokushima",
    "Tokyo",
    "Tottori",
    "Toyama",
    "Wakayama",
    "Yamagata",
    "Yamaguchi",
    "Yamanashi",
]

US_STATE_ZOOM = {state: 6.2 for state in US_STATES}
US_STATE_ZOOM.update(
    {
        "Alaska": 3.4,
        "Arizona": 5.7,
        "California": 5.2,
        "Colorado": 5.8,
        "Idaho": 5.9,
        "Maine": 6.4,
        "Massachusetts": 7.2,
        "Montana": 5.4,
        "Nevada": 5.6,
        "New Hampshire": 6.8,
        "New Mexico": 5.8,
        "New York": 6.2,
        "Oregon": 6.0,
        "Texas": 5.0,
        "Vermont": 6.8,
        "Washington": 6.0,
        "Wyoming": 5.9,
    }
)

CANADA_PROVINCE_ZOOM = {province: 5.2 for province in CANADA_PROVINCES}
CANADA_PROVINCE_ZOOM.update(
    {
        "British Columbia": 5.0,
        "Manitoba": 5.0,
        "New Brunswick": 6.0,
        "Newfoundland and Labrador": 5.6,
        "Northwest Territories": 4.5,
        "Nova Scotia": 6.0,
        "Nunavut": 4.0,
        "Ontario": 4.8,
        "Prince Edward Island": 6.6,
        "Quebec": 4.8,
        "Saskatchewan": 5.0,
        "Yukon": 4.5,
    }
)

JAPAN_PREFECTURE_ZOOM = {prefecture: 6.6 for prefecture in JAPAN_PREFECTURES}
JAPAN_PREFECTURE_ZOOM.update(
    {
        "Hokkaido": 5.8,
        "Okinawa": 6.0,
    }
)

STATE_ZOOM = {
    **US_STATE_ZOOM,
    **CANADA_PROVINCE_ZOOM,
    **JAPAN_PREFECTURE_ZOOM,
}
